# Generated by Django 3.2.5 on 2021-10-31 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFromEmployee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating_app.employee')),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating_app.service')),
            ],
            options={
                'verbose_name_plural': 'servicesFromEmployees',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('serviceFromEmployeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating_app.servicefromemployee')),
            ],
            options={
                'verbose_name_plural': 'ratings',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='shopId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating_app.shop'),
        ),
    ]
